// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sCTNSolution.Data.EF;

namespace sCTNSolution.Data.Migrations
{
    [DbContext(typeof(CTNKGContext))]
    partial class CTNKGContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sCTNSolution.Data.Entities.BangGiaNuoc", b =>
                {
                    b.Property<string>("MaBangGia")
                        .HasColumnName("Ma_Bang_Gia")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<double?>("GiaCoDinh")
                        .HasColumnName("Gia_Co_Dinh")
                        .HasColumnType("float");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnName("Ngay_Bat_Dau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnName("Ngay_Ket_Thuc")
                        .HasColumnType("datetime");

                    b.Property<int?>("NguonNuoc")
                        .HasColumnName("Nguon_Nuoc")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("MaBangGia")
                        .HasName("PK_BangGiaNuoc_1");

                    b.ToTable("BangGiaNuoc");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.BangGiaNuocTheoTram", b =>
                {
                    b.Property<string>("MaTram")
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaBangGia")
                        .HasColumnName("Ma_Bang_Gia")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnName("Ngay_Ap_Dung")
                        .HasColumnType("datetime");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<double?>("HeSo")
                        .HasColumnName("He_So")
                        .HasColumnType("float");

                    b.Property<int?>("MucGia")
                        .HasColumnName("Muc_Gia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnName("Ngay_Ket_Thuc")
                        .HasColumnType("datetime");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MaTram", "MaBangGia", "NgayApDung")
                        .HasName("PK_BangGiaNuocTheoTram_1");

                    b.HasIndex("MaBangGia");

                    b.ToTable("BangGiaNuocTheoTram");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.ChiPhiTram", b =>
                {
                    b.Property<string>("MaTram")
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ThangNam")
                        .HasColumnName("Thang_Nam")
                        .HasColumnType("datetime");

                    b.Property<int?>("Chastise")
                        .HasColumnType("int")
                        .HasComment("Phạt");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("Money")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.HasKey("MaTram", "ThangNam")
                        .HasName("PK_ChiPhiTram_1");

                    b.ToTable("ChiPhiTram");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.ChiPhiTramChiTiet", b =>
                {
                    b.Property<string>("MaTram")
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ThangNam")
                        .HasColumnName("Thang_Nam")
                        .HasColumnType("datetime");

                    b.Property<string>("MaLoaiChiPhi")
                        .HasColumnName("Ma_Loai_Chi_Phi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("NgayGhiNhan")
                        .HasColumnName("Ngay_Ghi_Nhan")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnName("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThayDoi")
                        .HasColumnName("Ngay_Thay_Doi")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnName("Nguoi_Tao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiThayDoi")
                        .HasColumnName("Nguoi_Thay_Doi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("MaTram", "ThangNam", "MaLoaiChiPhi");

                    b.HasIndex("MaLoaiChiPhi");

                    b.ToTable("ChiPhiTramChiTiet");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.ChiSoTramNuoc", b =>
                {
                    b.Property<string>("MaTram")
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ThangNam")
                        .HasColumnName("Thang_Nam")
                        .HasColumnType("datetime");

                    b.Property<int?>("ChenhLech")
                        .HasColumnName("Chenh_Lech")
                        .HasColumnType("int");

                    b.Property<int?>("ChiPhiKhac")
                        .HasColumnName("Chi_Phi_Khac")
                        .HasColumnType("int");

                    b.Property<int?>("ChiPhiMoiM3Nuoc")
                        .HasColumnName("Chi_Phi_Moi_M3_Nuoc")
                        .HasColumnType("int");

                    b.Property<int?>("ChiPhiVanHanh")
                        .HasColumnName("Chi_Phi_Van_Hanh")
                        .HasColumnType("int");

                    b.Property<double?>("Clorine")
                        .HasColumnType("float");

                    b.Property<int?>("ConLaiDuocLinh")
                        .HasColumnName("Con_Lai_Duoc_Linh")
                        .HasColumnType("int");

                    b.Property<int?>("CongTacPhi")
                        .HasColumnName("Cong_Tac_Phi")
                        .HasColumnType("int");

                    b.Property<double?>("Dau")
                        .HasColumnType("float");

                    b.Property<int?>("DhdKyNay")
                        .HasColumnName("DHD_Ky_Nay")
                        .HasColumnType("int");

                    b.Property<int?>("DhdKyTruoc")
                        .HasColumnName("DHD_Ky_Truoc")
                        .HasColumnType("int");

                    b.Property<int?>("DhdSuDung")
                        .HasColumnName("DHD_Su_Dung")
                        .HasColumnType("int");

                    b.Property<int?>("DhtKyNay")
                        .HasColumnName("DHT_Ky_Nay")
                        .HasColumnType("int");

                    b.Property<int?>("DhtKyTruoc")
                        .HasColumnName("DHT_Ky_Truoc")
                        .HasColumnType("int");

                    b.Property<int?>("DhtSuDung")
                        .HasColumnName("DHT_Su_Dung")
                        .HasColumnType("int");

                    b.Property<int?>("DienThoai")
                        .HasColumnName("Dien_Thoai")
                        .HasColumnType("int");

                    b.Property<int?>("DinhMuc")
                        .HasColumnName("Dinh_Muc")
                        .HasColumnType("int");

                    b.Property<int?>("DoanhThuKyNay")
                        .HasColumnName("Doanh_Thu_Ky_Nay")
                        .HasColumnType("int");

                    b.Property<int?>("DoanhThuKyTruoc")
                        .HasColumnName("Doanh_Thu_Ky_Truoc")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<double?>("GiaNuocBanRaBqChiPhi")
                        .HasColumnName("Gia_Nuoc_Ban_Ra_BQ_Chi_Phi")
                        .HasColumnType("float");

                    b.Property<int?>("Luong")
                        .HasColumnType("int");

                    b.Property<double?>("LuongNuocSxBqHo")
                        .HasColumnName("Luong_Nuoc_SX_BQ_Ho")
                        .HasColumnType("float");

                    b.Property<double?>("LuongNuocTtBqHo")
                        .HasColumnName("Luong_Nuoc_TT_BQ_Ho")
                        .HasColumnType("float");

                    b.Property<int?>("LuongTieuThu")
                        .HasColumnName("Luong_Tieu_Thu")
                        .HasColumnType("int");

                    b.Property<double?>("Nhot")
                        .HasColumnType("float");

                    b.Property<int?>("NoCaNhan")
                        .HasColumnName("No_Ca_Nhan")
                        .HasColumnType("int");

                    b.Property<int?>("NoCu")
                        .HasColumnName("No_Cu")
                        .HasColumnType("int");

                    b.Property<int?>("NoKhachHang")
                        .HasColumnName("No_Khach_Hang")
                        .HasColumnType("int");

                    b.Property<int?>("NoKyTruoc")
                        .HasColumnName("No_Ky_Truoc")
                        .HasColumnType("int");

                    b.Property<int?>("NopDu")
                        .HasColumnName("Nop_Du")
                        .HasColumnType("int");

                    b.Property<double?>("PhanNan")
                        .HasColumnName("Phan_Nan")
                        .HasColumnType("float");

                    b.Property<int?>("Phat")
                        .HasColumnType("int");

                    b.Property<double?>("Phen")
                        .HasColumnType("float");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SoGioLamViec")
                        .HasColumnName("So_Gio_Lam_Viec")
                        .HasColumnType("int");

                    b.Property<int?>("SoHoHoatDong")
                        .HasColumnName("So_Ho_Hoat_Dong")
                        .HasColumnType("int");

                    b.Property<int?>("SoHoaDon")
                        .HasColumnName("So_Hoa_Don")
                        .HasColumnType("int");

                    b.Property<int?>("SoTienDaNop")
                        .HasColumnName("So_Tien_Da_Nop")
                        .HasColumnType("int");

                    b.Property<int?>("SuaChua")
                        .HasColumnName("Sua_Chua")
                        .HasColumnType("int");

                    b.Property<int?>("ThatThoat")
                        .HasColumnName("That_Thoat")
                        .HasColumnType("int");

                    b.Property<int?>("ThatThoatDuoi22")
                        .HasColumnName("That_Thoat_Duoi22")
                        .HasColumnType("int");

                    b.Property<int?>("ThucTe")
                        .HasColumnName("Thuc_Te")
                        .HasColumnType("int");

                    b.Property<int?>("TienDien")
                        .HasColumnName("Tien_Dien")
                        .HasColumnType("int");

                    b.Property<bool?>("TinhTrang")
                        .HasColumnName("Tinh_Trang")
                        .HasColumnType("bit");

                    b.Property<int?>("TongChiPhi")
                        .HasColumnName("Tong_Chi_Phi")
                        .HasColumnType("int");

                    b.Property<int?>("TongNo")
                        .HasColumnName("Tong_No")
                        .HasColumnType("int");

                    b.Property<int?>("TongSoHo")
                        .HasColumnName("Tong_So_Ho")
                        .HasColumnType("int");

                    b.Property<double?>("TyLeDienKhaiThac")
                        .HasColumnName("Ty_Le_Dien_Khai_Thac")
                        .HasColumnType("float");

                    b.Property<double?>("TyLeDienTieuThu")
                        .HasColumnName("Ty_Le_Dien_Tieu_Thu")
                        .HasColumnType("float");

                    b.Property<double?>("TyLeSuDungNuoc")
                        .HasColumnName("Ty_Le_Su_Dung_Nuoc")
                        .HasColumnType("float");

                    b.Property<double?>("TyLeTtNuoc")
                        .HasColumnName("Ty_Le_TT_Nuoc")
                        .HasColumnType("float");

                    b.Property<int?>("VanPhongPham")
                        .HasColumnName("Van_Phong_Pham")
                        .HasColumnType("int");

                    b.Property<int?>("Xang")
                        .HasColumnType("int");

                    b.HasKey("MaTram", "ThangNam");

                    b.ToTable("ChiSoTramNuoc");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasColumnName("Ma_Chuc_Vu")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenChucVu")
                        .HasColumnName("Ten_Chuc_Vu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.ClorinePhenDau", b =>
                {
                    b.Property<string>("MaCpd")
                        .HasColumnName("Ma_CPD")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double?>("Clorine")
                        .HasColumnType("float");

                    b.Property<double?>("Dau")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTram")
                        .IsRequired()
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double?>("Phen")
                        .HasColumnType("float");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MaCpd")
                        .HasName("PK_ClorinePhenDau_1");

                    b.HasIndex("MaTram");

                    b.ToTable("ClorinePhenDau");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.Company", b =>
                {
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnName("Address_2")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Name2")
                        .IsRequired()
                        .HasColumnName("Name_2")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasColumnName("Phone_2")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.ToTable("Company");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.CongNoKhachHang", b =>
                {
                    b.Property<DateTime>("KyTinh")
                        .HasColumnName("Ky_Tinh")
                        .HasColumnType("datetime");

                    b.Property<string>("MaKh")
                        .HasColumnName("Ma_KH")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnName("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnName("Ngay_Thanh_Toan")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThayDoi")
                        .HasColumnName("Ngay_Thay_Doi")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiQuyetToan")
                        .HasColumnName("Nguoi_Quyet_Toan")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiTao")
                        .HasColumnName("Nguoi_Tao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiThayDoi")
                        .HasColumnName("Nguoi_Thay_Doi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SoSeri")
                        .HasColumnName("So_Seri")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double?>("SoTien")
                        .HasColumnName("So_Tien")
                        .HasColumnType("float");

                    b.Property<bool?>("TinhTrang")
                        .HasColumnName("Tinh_Trang")
                        .HasColumnType("bit");

                    b.HasKey("KyTinh", "MaKh")
                        .HasName("PK_CongNoKhachHang_1");

                    b.HasIndex("MaKh");

                    b.ToTable("CongNoKhachHang");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.DanhMucCum", b =>
                {
                    b.Property<string>("MaCum")
                        .HasColumnName("Ma_Cum")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenCum")
                        .HasColumnName("Ten_Cum")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("MaCum");

                    b.ToTable("DanhMucCum");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.DinhMucSuDung", b =>
                {
                    b.Property<string>("MaBangGia")
                        .HasColumnName("Ma_Bang_Gia")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaDinhMuc")
                        .HasColumnName("Ma_Dinh_Muc")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("DinhMuc")
                        .HasColumnName("Dinh_Muc")
                        .HasColumnType("int");

                    b.Property<double?>("DonGia")
                        .HasColumnName("Don_Gia")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnName("Ngay_Bat_Dau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnName("Ngay_Ket_Thuc")
                        .HasColumnType("datetime");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenDinhMuc")
                        .HasColumnName("Ten_Dinh_Muc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaBangGia", "MaDinhMuc")
                        .HasName("PK_BangDinhMucSuDung");

                    b.ToTable("DinhMucSuDung");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.DoanhThuTram", b =>
                {
                    b.Property<string>("MaTram")
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ThangNam")
                        .HasColumnName("Thang_Nam")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("DoanhThuDaCoThue")
                        .HasColumnName("Doanh_Thu_Da_Co_Thue")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("DoanhThuKyTruoc")
                        .HasColumnName("Doanh_Thu_Ky_Truoc")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("DoanhThuTruocThue")
                        .HasColumnName("Doanh_Thu_Truoc_Thue")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<decimal?>("NoCaNhan")
                        .HasColumnName("No_Ca_Nhan")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("NoKhachHang")
                        .HasColumnName("No_Khach_Hang")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("SoTienThuThuc")
                        .HasColumnName("So_Tien_Thu_Thuc")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TienThue")
                        .HasColumnName("Tien_Thue")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<bool?>("TinhTrang")
                        .HasColumnName("Tinh_Trang")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TongChiPhi")
                        .HasColumnName("Tong_Chi_Phi")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TongDoanhThu")
                        .HasColumnName("Tong_Doanh_Thu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TongSoTienCanThu")
                        .HasColumnName("Tong_So_Tien_Can_Thu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("Vat")
                        .HasColumnName("VAT")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("MaTram", "ThangNam");

                    b.ToTable("DoanhThuTram");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.DonViTinh", b =>
                {
                    b.Property<string>("MaDvt")
                        .HasColumnName("Ma_DVT")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenDvt")
                        .HasColumnName("Ten_DVT")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("MaDvt")
                        .HasName("PK_Don_Vi_Tinh");

                    b.ToTable("DonViTinh");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.DongHoKhongHoatDong", b =>
                {
                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MaNn")
                        .HasColumnName("Ma_NN")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenNn")
                        .HasColumnName("Ten_NN")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.ToTable("DongHoKhongHoatDong");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.GhiNhanThayDoiGiaVatTu", b =>
                {
                    b.Property<DateTime>("NgayApDung")
                        .HasColumnName("Ngay_Ap_Dung")
                        .HasColumnType("datetime");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnName("Ngay_Ket_Thuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnName("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThayDoi")
                        .HasColumnName("Ngay_Thay_Doi")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnName("Nguoi_Tao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiThayDoi")
                        .HasColumnName("Nguoi_Thay_Doi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("NgayApDung")
                        .HasName("PK_GhiNhanThayDoiGiaVatTu_1");

                    b.ToTable("GhiNhanThayDoiGiaVatTu");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.GiaVatTu", b =>
                {
                    b.Property<string>("MaVt")
                        .HasColumnName("Ma_VT")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnName("Ngay_Ap_Dung")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("DonGia")
                        .HasColumnName("Don_Gia")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnName("Ngay_Ket_Thuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnName("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThayDoi")
                        .HasColumnName("Ngay_Thay_Doi")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnName("Nguoi_Tao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiThayDoi")
                        .HasColumnName("Nguoi_Thay_Doi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MaVt", "NgayApDung");

                    b.HasIndex("NgayApDung");

                    b.ToTable("GiaVatTu");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.GroupFunction", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("IsReadOnly")
                        .HasColumnType("int");

                    b.Property<string>("Menu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Menu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SecurityButton")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("GroupFunction");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.GroupUser", b =>
                {
                    b.Property<string>("No")
                        .HasColumnName("No_")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("GroupGrant")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("No");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnName("Ma_Hoa_Don")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ChiSoCu")
                        .HasColumnName("Chi_So_Cu")
                        .HasColumnType("int");

                    b.Property<int?>("ChiSoMoi")
                        .HasColumnName("Chi_So_Moi")
                        .HasColumnType("int");

                    b.Property<bool?>("DaThanhToan")
                        .HasColumnName("Da_Thanh_Toan")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Dm10")
                        .HasColumnName("DM10")
                        .HasColumnType("numeric(5, 0)");

                    b.Property<decimal?>("Dm20")
                        .HasColumnName("DM20")
                        .HasColumnType("numeric(5, 0)");

                    b.Property<decimal?>("Dm30")
                        .HasColumnName("DM30")
                        .HasColumnType("numeric(5, 0)");

                    b.Property<decimal?>("Dm40")
                        .HasColumnName("DM40")
                        .HasColumnType("numeric(5, 0)");

                    b.Property<double?>("DonGiaTdm")
                        .HasColumnName("Don_Gia_TDM")
                        .HasColumnType("float");

                    b.Property<decimal?>("DonGiaVdm")
                        .HasColumnName("Don_Gia_VDM")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("KyTinh")
                        .HasColumnName("Ky_Tinh")
                        .HasColumnType("datetime");

                    b.Property<string>("MaKh")
                        .HasColumnName("Ma_KH")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnName("Ngay_Lap")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnName("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThayDoi")
                        .HasColumnName("Ngay_Thay_Doi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThu")
                        .HasColumnName("Ngay_Thu")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnName("Nguoi_Tao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiThayDoi")
                        .HasColumnName("Nguoi_Thay_Doi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("NguyenNhan")
                        .HasColumnName("Nguyen_Nhan")
                        .HasColumnType("int");

                    b.Property<string>("NhanVienGhiNuoc")
                        .HasColumnName("Nhan_Vien_Ghi_Nuoc")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NhanVienThuTien")
                        .HasColumnName("Nhan_Vien_Thu_Tien")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double?>("NoKyTruoc")
                        .HasColumnName("No_Ky_Truoc")
                        .HasColumnType("float");

                    b.Property<string>("PhanLoaiNuocSd")
                        .HasColumnName("Phan_Loai_Nuoc_SD")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<double?>("PhiNuocThai")
                        .HasColumnName("Phi_Nuoc_Thai")
                        .HasColumnType("float");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("SoM3")
                        .HasColumnName("So_M3")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("TenKh")
                        .HasColumnName("Ten_KH")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<double?>("ThanhTien")
                        .HasColumnName("Thanh_Tien")
                        .HasColumnType("float");

                    b.Property<decimal?>("TienBaoTri")
                        .HasColumnName("Tien_Bao_Tri")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<double?>("TienTdm")
                        .HasColumnName("Tien_TDM")
                        .HasColumnType("float");

                    b.Property<decimal?>("TienThueBao")
                        .HasColumnName("Tien_Thue_Bao")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<decimal?>("TienVdm")
                        .HasColumnName("Tien_VDM")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<double?>("TongTien")
                        .HasColumnName("Tong_Tien")
                        .HasColumnType("float");

                    b.Property<double?>("Vat")
                        .HasColumnName("VAT")
                        .HasColumnType("float");

                    b.HasKey("MaHoaDon")
                        .HasName("PK_HoaDon_1");

                    b.HasIndex("KyTinh");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.HopDongSuDung", b =>
                {
                    b.Property<string>("MaHd")
                        .HasColumnName("Ma_HD")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ChiPhiNhanCong")
                        .HasColumnName("Chi_Phi_Nhan_Cong")
                        .HasColumnType("int");

                    b.Property<int?>("ChiPhiVanChuyen")
                        .HasColumnName("Chi_Phi_Van_Chuyen")
                        .HasColumnType("int");

                    b.Property<double?>("ChieuDaiOng")
                        .HasColumnName("Chieu_Dai_Ong")
                        .HasColumnType("float");

                    b.Property<int?>("DanGop")
                        .HasColumnName("Dan_Gop")
                        .HasColumnType("int");

                    b.Property<string>("DanhBo")
                        .HasColumnName("Danh_Bo")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("DinhKemFile")
                        .HasColumnName("Dinh_Kem_FILE")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("DinhMuc")
                        .HasColumnName("Dinh_Muc")
                        .HasColumnType("int");

                    b.Property<int?>("DuongKinh")
                        .HasColumnName("Duong_Kinh")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("HieuDongHo")
                        .HasColumnName("Hieu_Dong_Ho")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LoaiDongHo")
                        .HasColumnName("Loai_Dong_Ho")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LoaiOng")
                        .HasColumnName("Loai_Ong")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("LuongCanSuDungTrongThang")
                        .HasColumnName("Luong_Can_Su_Dung_Trong_Thang")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("MaDongHo")
                        .HasColumnName("Ma_Dong_Ho")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaKh")
                        .HasColumnName("Ma_KH")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnName("Ngay_Ky")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayLapDh")
                        .HasColumnName("Ngay_Lap_DH")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnName("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThayDoi")
                        .HasColumnName("Ngay_Thay_Doi")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnName("Nguoi_Tao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiThayDoi")
                        .HasColumnName("Nguoi_Thay_Doi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("NhaNuocHoTro")
                        .HasColumnName("Nha_Nuoc_Ho_Tro")
                        .HasColumnType("int");

                    b.Property<string>("PhanLoaiNuocSd")
                        .HasColumnName("Phan_Loai_Nuoc_SD")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("SoGioCungCapNgay")
                        .HasColumnName("So_Gio_Cung_Cap_Ngay")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<long?>("SoHd")
                        .HasColumnName("So_HD")
                        .HasColumnType("bigint");

                    b.Property<string>("ThanhToan")
                        .HasColumnName("Thanh_Toan")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ThoiGianBaoHanhDh")
                        .HasColumnName("Thoi_Gian_Bao_Hanh_DH")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MaHd");

                    b.HasIndex("MaKh");

                    b.HasIndex("PhanLoaiNuocSd");

                    b.ToTable("HopDongSuDung");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasColumnName("Ma_KH")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ApKh")
                        .HasColumnName("Ap_KH")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Cmnd")
                        .HasColumnName("CMND")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DienChinhSach")
                        .HasColumnName("Dien_Chinh_Sach")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DienThoai")
                        .HasColumnName("Dien_Thoai")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool?>("GioiTinh")
                        .HasColumnName("Gioi_Tinh")
                        .HasColumnType("bit");

                    b.Property<string>("MaDh")
                        .HasColumnName("Ma_DH")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaTram")
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaTuyen")
                        .HasColumnName("Ma_Tuyen")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MstKh")
                        .HasColumnName("MST_KH")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Mstk")
                        .HasColumnName("MSTK")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<string>("NganHang")
                        .HasColumnName("Ngan_Hang")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnName("Ngay_Cap")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgaySuDung")
                        .HasColumnName("Ngay_Su_Dung")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTamNgung")
                        .HasColumnName("Ngay_Tam_Ngung")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnName("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThayDoi")
                        .HasColumnName("Ngay_Thay_Doi")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnName("Nguoi_Tao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiThayDoi")
                        .HasColumnName("Nguoi_Thay_Doi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NoiCap")
                        .HasColumnName("Noi_Cap")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Nu")
                        .HasColumnType("int");

                    b.Property<string>("QuanHuyen")
                        .HasColumnName("Quan_Huyen")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SoNha")
                        .HasColumnName("So_Nha")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("SoNhanKhau")
                        .HasColumnName("So_Nhan_Khau")
                        .HasColumnType("int");

                    b.Property<bool?>("TamNgungSd")
                        .HasColumnName("Tam_Ngung_SD")
                        .HasColumnType("bit");

                    b.Property<string>("TenKh")
                        .HasColumnName("Ten_KH")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<decimal?>("TienLddh")
                        .HasColumnName("Tien_LDDH")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("TinhThanh")
                        .HasColumnName("Tinh_Thanh")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ToKh")
                        .HasColumnName("To_KH")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("XaPhuong")
                        .HasColumnName("Xa_Phuong")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MaKh")
                        .HasName("PK_KhachHang_1");

                    b.HasIndex("MaTram");

                    b.HasIndex("QuanHuyen");

                    b.HasIndex("TinhThanh");

                    b.HasIndex("XaPhuong");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.KyXuatHoaDon", b =>
                {
                    b.Property<DateTime>("MaKyTinh")
                        .HasColumnName("Ma_Ky_Tinh")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnName("Den_Ngay")
                        .HasColumnType("datetime");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnName("Tu_Ngay")
                        .HasColumnType("datetime");

                    b.HasKey("MaKyTinh")
                        .HasName("PK_KyTinh");

                    b.ToTable("KyXuatHoaDon");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.LoaiChiPhi", b =>
                {
                    b.Property<string>("MaLoaiChiPhi")
                        .HasColumnName("Ma_Loai_Chi_Phi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("ChiPhi")
                        .HasColumnName("Chi_Phi")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoaiChiPhi")
                        .HasColumnName("Ten_Loai_Chi_Phi")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool?>("TinhTrang")
                        .HasColumnName("Tinh_Trang")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiChiPhi");

                    b.ToTable("LoaiChiPhi");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.LoaiVatTu", b =>
                {
                    b.Property<string>("MaLoaiVt")
                        .HasColumnName("Ma_Loai_VT")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoaiVt")
                        .HasColumnName("Ten_Loai_VT")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("MaLoaiVt")
                        .HasName("PK_Loai_VT");

                    b.ToTable("LoaiVatTu");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.Login", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("GroupUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("IsUsed")
                        .HasColumnType("int");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnName("UserID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Name");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.MainFunction", b =>
                {
                    b.Property<string>("FormName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Menu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Menu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("FormName");

                    b.ToTable("MainFunction");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasColumnName("Ma_NV")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ChucVu")
                        .HasColumnName("Chuc_Vu")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DiaChi")
                        .HasColumnName("Dia_Chi")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("DienThoai")
                        .HasColumnName("Dien_Thoai")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool?>("GioiTinh")
                        .HasColumnName("Gioi_Tinh")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnName("Ngay_Sinh")
                        .HasColumnType("datetime");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenNv")
                        .HasColumnName("Ten_NV")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("MaNv")
                        .HasName("PK_NhanVien_1");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.NhanVienVanHanhTram", b =>
                {
                    b.Property<string>("MaNv")
                        .HasColumnName("Ma_NV")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaTram")
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DienThoaiDd")
                        .HasColumnName("Dien_Thoai_DD")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DienThoaiNhaRieng")
                        .HasColumnName("Dien_Thoai_Nha_Rieng")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnName("Ngay_Bat_Dau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnName("Ngay_Ket_Thuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKyHopDong")
                        .HasColumnName("Ngay_Ky_Hop_Dong")
                        .HasColumnType("datetime");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("TinhTrang")
                        .HasColumnName("Tinh_Trang")
                        .HasColumnType("bit");

                    b.Property<string>("TrinhDoChuyenMon")
                        .HasColumnName("Trinh_Do_Chuyen_Mon")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MaNv", "MaTram")
                        .HasName("PK_NhanVienVanHanhTram_1");

                    b.HasIndex("MaTram");

                    b.ToTable("NhanVienVanHanhTram");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.NhatKyBaoDuong", b =>
                {
                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaTram")
                        .IsRequired()
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayBaoTri")
                        .HasColumnName("Ngay_Bao_Tri")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDung")
                        .HasColumnName("Noi_Dung")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.ToTable("NhatKyBaoDuong");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.QuanHuyen", b =>
                {
                    b.Property<string>("MaQuanHuyen")
                        .HasColumnName("Ma_Quan_Huyen")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("MaTinhThanh")
                        .HasColumnName("Ma_Tinh_Thanh")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenQuanHuyen")
                        .HasColumnName("Ten_Quan_Huyen")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("MaQuanHuyen");

                    b.ToTable("QuanHuyen");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.TaiSan", b =>
                {
                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<string>("MaTaiSan")
                        .IsRequired()
                        .HasColumnName("Ma_Tai_San")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .HasColumnName("RowID")
                        .HasColumnType("int");

                    b.Property<string>("TenTaiSan")
                        .HasColumnName("Ten_Tai_San")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.ToTable("TaiSan");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.TaiSanTram", b =>
                {
                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaTaiSan")
                        .HasColumnName("Ma_Tai_San")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("MaTram")
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MoTa")
                        .HasColumnName("Mo_Ta")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SoLuong")
                        .HasColumnName("So_Luong")
                        .HasColumnType("int");

                    b.ToTable("TaiSanTram");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.TinhThanh", b =>
                {
                    b.Property<string>("MaTinhThanh")
                        .HasColumnName("Ma_Tinh_Thanh")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTinhThanh")
                        .HasColumnName("Ten_Tinh_Thanh")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("MaTinhThanh");

                    b.ToTable("TinhThanh");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.TramNuoc", b =>
                {
                    b.Property<string>("MaTram")
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("CongSuat")
                        .HasColumnName("Cong_Suat")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool?>("KichHoat")
                        .HasColumnName("Kich_Hoat")
                        .HasColumnType("bit");

                    b.Property<string>("MaCum")
                        .HasColumnName("Ma_Cum")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaDongHo")
                        .HasColumnName("Ma_Dong_Ho")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NgayHoatDong")
                        .HasColumnName("Ngay_Hoat_Dong")
                        .HasColumnType("datetime");

                    b.Property<int?>("NguonNuoc")
                        .HasColumnName("Nguon_Nuoc")
                        .HasColumnType("int");

                    b.Property<string>("QuanHuyen")
                        .HasColumnName("Quan_Huyen")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SoHoDuKien")
                        .HasColumnName("So_Ho_Du_Kien")
                        .HasColumnType("int");

                    b.Property<string>("SoNha")
                        .HasColumnName("So_Nha")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TenTram")
                        .IsRequired()
                        .HasColumnName("Ten_Tram")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<decimal?>("TheTichBe")
                        .HasColumnName("The_Tich_Be")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("TinhThanh")
                        .HasColumnName("Tinh_Thanh")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("TongSoHo")
                        .HasColumnName("Tong_So_Ho")
                        .HasColumnType("int");

                    b.Property<string>("XaPhuong")
                        .HasColumnName("Xa_Phuong")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MaTram")
                        .HasName("PK_TramNuoc_1");

                    b.ToTable("TramNuoc");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.Tuyen", b =>
                {
                    b.Property<string>("MaTram")
                        .HasColumnName("Ma_Tram")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaTuyen")
                        .HasColumnName("Ma_Tuyen")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTuyen")
                        .HasColumnName("Ten_Tuyen")
                        .HasColumnType("nvarchar(350)")
                        .HasMaxLength(350);

                    b.HasKey("MaTram", "MaTuyen");

                    b.ToTable("Tuyen");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.VatTu", b =>
                {
                    b.Property<string>("MaVt")
                        .HasColumnName("Ma_VT")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DonViTinh")
                        .HasColumnName("Don_Vi_Tinh")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("LoaiVt")
                        .HasColumnName("Loai_VT")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NhanHieu")
                        .HasColumnName("Nhan_Hieu")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenVatTu")
                        .HasColumnName("Ten_Vat_Tu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("MaVt");

                    b.HasIndex("DonViTinh");

                    b.HasIndex("LoaiVt");

                    b.ToTable("VatTu");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.VatTuCongTy", b =>
                {
                    b.Property<string>("MaVt")
                        .HasColumnName("Ma_VT")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnName("Ngay_Nhap")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("DonGiaNhap")
                        .HasColumnName("Don_Gia_Nhap")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnName("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThayDoi")
                        .HasColumnName("Ngay_Thay_Doi")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnName("Nguoi_Tao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiThayDoi")
                        .HasColumnName("Nguoi_Thay_Doi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("SoLuong")
                        .HasColumnName("So_Luong")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("ThanhTienNhap")
                        .HasColumnName("Thanh_Tien_Nhap")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("MaVt", "NgayNhap")
                        .HasName("PK_VatTuTram");

                    b.ToTable("VatTuCongTy");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.VatTuKhachHang", b =>
                {
                    b.Property<string>("MaHd")
                        .HasColumnName("Ma_HD")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaVt")
                        .HasColumnName("Ma_VT")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("DonGia")
                        .HasColumnName("Don_Gia")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnName("Ngay_Lap")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnName("Ngay_Tao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThayDoi")
                        .HasColumnName("Ngay_Thay_Doi")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnName("Nguoi_Tao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiThayDoi")
                        .HasColumnName("Nguoi_Thay_Doi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("SoLuong")
                        .HasColumnName("So_Luong")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnName("Thanh_Tien")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("MaHd", "MaVt")
                        .HasName("PK_VatTuKhachHang_1");

                    b.ToTable("VatTuKhachHang");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.XaPhuong", b =>
                {
                    b.Property<string>("MaXaPhuong")
                        .HasColumnName("Ma_Xa_Phuong")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnName("Ghi_Chu")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("MaQuanHuyen")
                        .HasColumnName("Ma_Quan_Huyen")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaTinhThanh")
                        .HasColumnName("Ma_Tinh_Thanh")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RowID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenXaPhuong")
                        .HasColumnName("Ten_Xa_Phuong")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("MaXaPhuong");

                    b.ToTable("XaPhuong");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.BangGiaNuocTheoTram", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.BangGiaNuoc", "MaBangGiaNavigation")
                        .WithMany("BangGiaNuocTheoTram")
                        .HasForeignKey("MaBangGia")
                        .HasConstraintName("FK_BangGiaNuocTheoTram_BangGiaNuoc")
                        .IsRequired();
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.ChiPhiTramChiTiet", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.LoaiChiPhi", "MaLoaiChiPhiNavigation")
                        .WithMany("ChiPhiTramChiTiet")
                        .HasForeignKey("MaLoaiChiPhi")
                        .HasConstraintName("FK_ChiPhiTramChiTiet_LoaiChiPhi")
                        .IsRequired();

                    b.HasOne("sCTNSolution.Data.Entities.ChiPhiTram", "ChiPhiTram")
                        .WithMany("ChiPhiTramChiTiet")
                        .HasForeignKey("MaTram", "ThangNam")
                        .HasConstraintName("FK_ChiPhiTramChiTiet_ChiPhiTram")
                        .IsRequired();
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.ChiSoTramNuoc", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.TramNuoc", "MaTramNavigation")
                        .WithMany("ChiSoTramNuoc")
                        .HasForeignKey("MaTram")
                        .HasConstraintName("FK_ChiSoTramNuoc_TramNuoc")
                        .IsRequired();
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.ClorinePhenDau", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.TramNuoc", "MaTramNavigation")
                        .WithMany("ClorinePhenDau")
                        .HasForeignKey("MaTram")
                        .HasConstraintName("FK_ClorinePhenDau_TramNuoc")
                        .IsRequired();
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.CongNoKhachHang", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.KyXuatHoaDon", "KyTinhNavigation")
                        .WithMany("CongNoKhachHang")
                        .HasForeignKey("KyTinh")
                        .HasConstraintName("FK_CongNoKhachHang_KyXuatHoaDon")
                        .IsRequired();

                    b.HasOne("sCTNSolution.Data.Entities.KhachHang", "MaKhNavigation")
                        .WithMany("CongNoKhachHang")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_CongNoKhachHang_KhachHang")
                        .IsRequired();
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.GiaVatTu", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.VatTu", "MaVtNavigation")
                        .WithMany("GiaVatTu")
                        .HasForeignKey("MaVt")
                        .HasConstraintName("FK_GiaVatTu_VatTu")
                        .IsRequired();

                    b.HasOne("sCTNSolution.Data.Entities.GhiNhanThayDoiGiaVatTu", "NgayApDungNavigation")
                        .WithMany("GiaVatTu")
                        .HasForeignKey("NgayApDung")
                        .HasConstraintName("FK_GiaVatTu_GhiNhanThayDoiGiaVatTu")
                        .IsRequired();
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.HoaDon", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.KyXuatHoaDon", "KyTinhNavigation")
                        .WithMany("HoaDon")
                        .HasForeignKey("KyTinh")
                        .HasConstraintName("FK_HoaDon_KyXuatHoaDon");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.HopDongSuDung", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.KhachHang", "MaKhNavigation")
                        .WithMany("HopDongSuDung")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_HopDongSuDung_KhachHang");

                    b.HasOne("sCTNSolution.Data.Entities.BangGiaNuoc", "PhanLoaiNuocSdNavigation")
                        .WithMany("HopDongSuDung")
                        .HasForeignKey("PhanLoaiNuocSd")
                        .HasConstraintName("FK_HopDongSuDung_BangGiaNuoc");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.KhachHang", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.TramNuoc", "MaTramNavigation")
                        .WithMany("KhachHang")
                        .HasForeignKey("MaTram")
                        .HasConstraintName("FK_KhachHang_TramNuoc");

                    b.HasOne("sCTNSolution.Data.Entities.QuanHuyen", "QuanHuyenNavigation")
                        .WithMany("KhachHang")
                        .HasForeignKey("QuanHuyen")
                        .HasConstraintName("FK_KhachHang_QuanHuyen");

                    b.HasOne("sCTNSolution.Data.Entities.TinhThanh", "TinhThanhNavigation")
                        .WithMany("KhachHang")
                        .HasForeignKey("TinhThanh")
                        .HasConstraintName("FK_KhachHang_TinhThanh");

                    b.HasOne("sCTNSolution.Data.Entities.XaPhuong", "XaPhuongNavigation")
                        .WithMany("KhachHang")
                        .HasForeignKey("XaPhuong")
                        .HasConstraintName("FK_KhachHang_XaPhuong");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.NhanVienVanHanhTram", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.NhanVien", "MaNvNavigation")
                        .WithMany("NhanVienVanHanhTram")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK_NhanVienVanHanhTram_NhanVien")
                        .IsRequired();

                    b.HasOne("sCTNSolution.Data.Entities.TramNuoc", "MaTramNavigation")
                        .WithMany("NhanVienVanHanhTram")
                        .HasForeignKey("MaTram")
                        .HasConstraintName("FK_NhanVienVanHanhTram_TramNuoc")
                        .IsRequired();
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.VatTu", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.DonViTinh", "DonViTinhNavigation")
                        .WithMany("VatTu")
                        .HasForeignKey("DonViTinh")
                        .HasConstraintName("FK_VatTu_DonViTinh");

                    b.HasOne("sCTNSolution.Data.Entities.LoaiVatTu", "LoaiVtNavigation")
                        .WithMany("VatTu")
                        .HasForeignKey("LoaiVt")
                        .HasConstraintName("FK_VatTu_LoaiVatTu");
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.VatTuCongTy", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.VatTu", "MaVtNavigation")
                        .WithMany("VatTuCongTy")
                        .HasForeignKey("MaVt")
                        .HasConstraintName("FK_VatTuTram_VatTu")
                        .IsRequired();
                });

            modelBuilder.Entity("sCTNSolution.Data.Entities.VatTuKhachHang", b =>
                {
                    b.HasOne("sCTNSolution.Data.Entities.HopDongSuDung", "MaHdNavigation")
                        .WithMany("VatTuKhachHang")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("FK_VatTuKhachHang_HopDongSuDung")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
